name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  weather_icons: ^3.0.0
  country_flags: ^4.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  shimmer_animation: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  fl_chart: ^1.1.1
  location: ^8.0.1
  shared_preferences: ^2.5.4
  timezone: ^0.10.1
  dart_either: ^2.0.0
  get_it: ^9.2.0
  fpdart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true